Version info: [INFO]    [000.000000]  PlusLib version: 1.4.0 [INFO]    [000.005000]  Plus SVN revision: 1371 [INFO]    [000.013000]  Supported tracker devices:   - Ascension3DG (ver: Plus-1.4.0)   - BrachyTracker (ver: Plus-1.4.0)   - CertusTracker (ver: Optotrak API (Win32 DLL Version) Version 3.01.03)   - FakeTracker (ver: Plus-1.4.0)   - SavedDataset (ver: Plus-1.4.0)
[INFO]    [000.149000]  Supported video capturing devices:
  - ICCapturing (ver: The Imaging Source UDSHL-3.1)
  - NoiseVideo (ver: Plus-1.4.0)
  - SavedDataset (ver: Plus-1.4.0)
  - SonixPortaVideo (ver: UltrasonixSDK-5.7.1)
  - SonixVideo (ver: UltrasonixSDK-5.7.1)


Fixed tickets:

378	Segmentation error with iCal phantom 
287	Standardize comments in Plus
387	Revise tracked frame status field
395	Fix PhantomRegistration 
213	Add tracked ultrasound acquisition functionality to fCal
302	Revise configuration files
310	Remove enums from vtkTracker 
311	Use tool transform name in TrackedFrame instead of ToolName
312	Create a new Renderer common widget
313	DataCollector  simulator: Make DataCollector generatable from sequence metafile 
314	Remove calibrated transform from tracker 
333	PlusLib design: Move TrackedFrame related files to PlusCommon
345	Move cursor outside of the window for sikuli tests
360	Create PlusVersion application to retrieve Plus version and build option information
361	Remove deprecated methods from vtkBrachyStepperPhantomRegistrationAlgo
372	Make GUI testing in PlusApp optional
373	ApplicationVerifier found an error: NULL handle passed as parameter.
375	Change the Open functions in fCal to Import
376	Add options icon in fCal
377	Relative transform computation should be implemented in the tracking base classes
379	PlusBuild fails with errors if USBECGBOX option is turned on during configuration.
380	fCal crash when it cannot find STL models
381	Ulterius SDK version change should automatically update the SDK directory location
382	Reconstructed volume saving to metafile
385	New class for resolving transform path
386	Move show devices checkbox to toolbar
388	Define image message broadcasting port number in ImageAcquisition XML data
390	ProbeCalibrationAlgo: save spatial calibration result
391	PivotCalibrationAlgo: read and write calibration result to xml 
392	Make Ulterius get/set functions to communicate directly with the US imaging device
394	Create and use PlusTransformName class
398	PlusBuild update and nightly test script
402	Fix compilation errors in NDI and Polaris tracker classes
403	Create EditSeqMetaFile for sequence metafile editing
404	Display US probe position model relative to the image
406	Create a tutorial that describes how to perform landmark registration
408	Move CustomTransforms element from PhantomDefinition to CoordinateDefinitions
409	Create new vtkDisplayableObject type for visualization of axes
410	Fix OpenIGTLinkBroadcaster and test
413	problem with timestamps when using faketracker on Sonix RP