COMP: Use itkMacro.h instead of itkExceptionObject.h directly
Handles errors such as:
C:\P\PR19_x64-2\itk-int\include\ITK-5.1\itkExceptionObject.h(19): fatal error C1189: #error:  "Do not include itkExceptionObject.h directly,  include itkMacro.h instead." [C:\P\PR19_x64-2\PlusLib-bin\src\Utilities\Ransac\planeEstimation.vcxproj]

See https://github.com/InsightSoftwareConsortium/ITK/commit/ad0007e8868e4e51825c2f56a1e59a56bf99b69e