re #1063: Fixed the following errors: error C2653: 'TrackedFrame' : is not a class or namespace name error C2065: 'FieldMapType' : undeclared identifier error C2146: syntax error   : missing